config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

post '/attachment_file_field/upload', to: 'attachment_file_field#upload', as: :file_field_upload

app/controllers/attachment_file_field_controller.rb
# Redmine - project management software
# Copyright (C) 2006-2016  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class AttachmentFileFieldController < ApplicationController
  before_filter :find_editable_attachments, :only => [:update]

  def upload
    # Make sure that API users get used to set this content type
    # as it won't trigger Rails' automatic parsing of the request body for parameters
    unless request.content_type == 'application/octet-stream'
      render :nothing => true, :status => 406
      return
    end

    @attachment = Attachment.new(:file => request.raw_post)
    @attachment.author = User.current
    @attachment.filename = params[:filename].presence || Redmine::Utils.random_hex(16)
    @attachment.content_type = params[:content_type].presence
    saved = @attachment.save

    respond_to do |format|
      format.js {
        render json: {id: @attachment.id}
      }
    end
  end

end

app/views/custom_fields/formats/_file.html.erb
<p style="display:none;">
  <%= f.text_area :possible_values, :value => @custom_field.possible_values.to_a.join("\n"), :rows => 15 %>
</p>

<%= javascript_include_tag 'select_list_move', plugin: 'redmine_file_custom_field' %>
<p>
  <table class="query-columns">
    <tr>
      <td style="padding-left:0">
        <%= label_tag "available_file_types", l(:description_available_file_types), :style => "margin-left:-50px; overflow-wrap: normal;"%>
        <br />
        <%= select_tag 'available_file_types', options_for_select(RedmineFileCustomField::ContentTypes::TYPES), :multiple => true, :size => 10, :style => "width:200px", :ondblclick => "moveOptions(this.form.available_file_types, this.form.selected_file_types);" %>
      </td>
      <td class="buttons">
        <input type="button" value="&#8594;"
         onclick="moveOptions(this.form.available_file_types, this.form.selected_file_types);" /><br />
        <input type="button" value="&#8592;"
         onclick="moveOptions(this.form.selected_file_types, this.form.available_file_types);" />
      </td>
      <td>
        <%= label_tag "selected_file_types", l(:description_selected_file_types), :style => "margin-left:-50px; overflow-wrap: normal;" %>
        <br />
        <%= select_tag 'selected_file_types', options_for_select([]), :id => 'selected_file_types', :multiple => true, :size => 10, :style => "width:200px", :ondblclick => "moveOptions(this.form.selected_file_types, this.form.available_file_types);" %>
      </td>
      <td class="buttons">
        <input type="button" id="Ihhh" value="&#8648;" onclick="moveOptionTop(this.form.selected_file_types);" /><br />
        <input type="button" value="&#8593;" onclick="moveOptionUp(this.form.selected_file_types);" /><br />
        <input type="button" value="&#8595;" onclick="moveOptionDown(this.form.selected_file_types);" /><br />
        <input type="button" value="&#8650;" onclick="moveOptionBottom(this.form.selected_file_types);" />
      </td>
    </tr>
  </table>
</p>

<script type="text/javascript">


  $( document ).ready(function() {
    var atual_value = $("#custom_field_possible_values").val().split("\n");

    $.each(atual_value, function(key, value) {
      $('#available_file_types').find('option[value="'+value+'"]').detach().prependTo($('#selected_file_types'));
    });

    $('#custom_field_form').attr('onsubmit', 'selectAllOptions("selected_file_types", "custom_field_possible_values");');
  });
</script>

app/views/redmine_file_custom_field/_issue_form_hook.html.erb
<%= javascript_tag do %>
  $(document).ready(function() {
    $("#attributes input[type='file']").on('change', function() {
      console.log(this);
      function addInputFiles(inputEl) {
        var clearedFileInput = $(inputEl).clone().val('');

        if ($.ajaxSettings.xhr().upload && inputEl.files) {
          uploadAndAttachFiles(inputEl.files, inputEl);
        } else {
          // alert("Seu browser não possui compatibilidade");
        }
      }

      function uploadAndAttachFiles(files, inputEl) {
        $.each(files, function() {addFile(inputEl, this, true);});
      }

      function addFile(inputEl, file, eagerUpload) {
        ajaxUpload(file, 1, inputEl);
      }

      function ajaxUpload(file, attachmentId, inputEl) {
        actualUpload(file, attachmentId, inputEl);
      }

      function actualUpload(file, attachmentId, inputEl) {
        uploadBlob(file, '<%= file_field_upload_path(format: :js)  %>', attachmentId, {},inputEl);
      }

      function uploadBlob(blob, uploadUrl, attachmentId, options, inputEl) {
        uploadUrl = uploadUrl + '?attachment_id=' + attachmentId;
        if (blob instanceof window.File) {
          uploadUrl += '&filename=' + encodeURIComponent(blob.name);
          uploadUrl += '&content_type=' + encodeURIComponent(blob.type);
        }

        return $.ajax(uploadUrl, {
          type: 'POST',
          dataType : 'json',
          contentType: 'application/octet-stream',
          beforeSend: function(jqXhr, settings) {
            $('#ajax-indicator').show();
            settings.data = blob;
          },
          data: blob,
          cache: false,
          processData: false,
          success: function (result) {
            $('#ajax-indicator').hide();
            $(inputEl).parent().find("input[type='hidden']").val(result['id']);
          },
          error: function (jqxhr, status, errorThrown) {
            alert("Failure, Unable to recieve content")
            alert(jqxhr.responseText);
          }
        });
      }

      addInputFiles(this);
    });
  });
<% end %>

app/views/settings/_redmine_file_custom_field.html.erb
<table>
  <tbody>
    <tr>
      <td>Validar com antivirus (necesário instalar o clamd)</td>
      <td>
        <%= check_box_tag 'settings[scan_for_virus]', true, settings['scan_for_virus'] %>
      </td>
    </tr>
  </tbody>
</table>